# Generated by Django 4.0.6 on 2022-08-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_deathdata_severedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=250)),
                ('provance_name', models.CharField(max_length=250)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeathsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=250)),
                ('provance_name', models.CharField(max_length=250)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MalariaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=250)),
                ('casename', models.CharField(max_length=250)),
                ('provance_name', models.CharField(max_length=250)),
                ('value', models.FloatField()),
            ],
        ),
    ]
