# Generated by Django 4.0.6 on 2022-08-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_casesdata_deathsdata_malariadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casesdata',
            old_name='provance_name',
            new_name='province_name',
        ),
        migrations.RenameField(
            model_name='malariadata',
            old_name='casename',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='malariadata',
            old_name='provance_name',
            new_name='province_name',
        ),
    ]
