# Generated by Django 4.0.6 on 2022-08-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_provance_name_casesdata_province_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deathsdata',
            old_name='provance_name',
            new_name='province_name',
        ),
    ]
