# Generated by Django 4.0.6 on 2022-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_provance_name_deathsdata_province_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadcsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=255)),
                ('province_name', models.CharField(default='', max_length=250)),
                ('cases', models.CharField(default='', max_length=255)),
                ('death_cases', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
