# Generated by Django 4.0.6 on 2022-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_uploadcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='cases',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='death_cases',
            field=models.FloatField(),
        ),
    ]
