# Generated by Django 4.0.6 on 2022-09-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_uploadcsv_cases_alter_uploadcsv_death_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='cases',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='death_cases',
            field=models.FloatField(),
        ),
    ]
