# Generated by Django 4.0.6 on 2022-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_uploadcsv_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='cases',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='death_cases',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='year',
            field=models.CharField(default='', max_length=255),
        ),
    ]
